### ISSUE TITLE
throw new DiscordAPIError_1.DiscordAPIError(data, data.code, res.status, method, url);

### ISSUE THREAD

**Issue by ChiropracticBender** [gonzyui/Discord-Template-V13#8]
```[28-09-2021 17:25:40]: [Database] Successfully connected to the database! (Latency: 87ms)
/Users/server/Discord-Template-V13/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:198
                throw new DiscordAPIError_1.DiscordAPIError(data, data.code, res.status, method, url);
                      ^

DiscordAPIError[50035]: Invalid Form Body
options[0].type[NUMBER_TYPE_COERCE]: Value "STRING" is not int.
type[NUMBER_TYPE_COERCE]: Value "CHAT_INPUT" is not int.
    at SequentialHandler.runRequest (/Users/server/Discord-Template-V13/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/Users/server/Discord-Template-V13/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:99:20) {
  rawError: {
    code: 50035,
    errors: {
      options: { '0': { type: { _errors: [Array] } } },
      type: {
        _errors: [
          {
            code: 'NUMBER_TYPE_COERCE',
            message: 'Value "CHAT_INPUT" is not int.'
          }
        ]
      }
    },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'post',
  url: 'https://discord.com/api/v9/applications/891535753446834207/commands'
}```

**Comment by gonzyui** [comment]
fixed in new commits
